import turtle
t=turtle.Pen()
t.shape("turtle")
t.pencolor("red")
t.forward(100)
t.right(90)
t.pencolor("blue")
t.forward(100)
t.right(90)
t.pencolor("violet")
t.forward(100)
t.right(90)
t.pencolor("green")
t.forward(100)
turtle.done()
